version: '3.7'  
services:  
  php:
    build: ./php/
    restart: on-failure
#    environment:
#      TIMEZONE: Europe/Novosibirsk
    user: 1000:1000
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ../:/app
    working_dir: /app

  webserver:
    image: nginx:1.11
    restart: on-failure
    depends_on:
      - php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../:/app
    ports:
      - 8080:80

  composer:
    image: composer:1.4
    volumes:
      - ../:/app
    working_dir: /app
